version: '3.8'
services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD='mysecretpassword'
  
  backend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.backend
    ports:
      - 8080:8080
    depends_on:
      - postgres
  
  
      