FROM oven/bun:1

WORKDIR /usr/src/app

COPY ./apps/http-server ./apps/http-server
COPY ./packages ./packages
COPY ./bun.lock ./bun.lock
COPY ./package.json ./package.json
COPY ./package-lock.json ./package-lock.json
COPY ./turbo.json ./turbo.json

RUN bun install
RUN bun db:generate

EXPOSE 8080

CMD [ "bun", "run", "start:http" ]