FROM oven/bun:1

WORKDIR /usr/src/app

ARG DATABASE_URL

COPY ./apps/ws-server ./apps/ws-server
COPY ./packages ./packages
COPY ./bun.lock ./bun.lock
COPY ./package.json ./package.json
COPY ./package-lock.json ./package-lock.json
COPY ./turbo.json dest./turbo.json

RUN bun install
RUN bun db:generate
RUN DATABASE_URL=${DATABASE_URL} bun run build

EXPOSE 3000

CMD [ "bun", "run", "start:wed" ]