name: deploying backend docker image ot dockerhub and vm

on:
  push:
    branches: [ main ]

jobs:
  build_the_docker_image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v2

      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.backend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/todo-application:${{ github.sha }}

      - name: ssh into vm and deploy the docker image for backend
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VM_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            whoami
            echo "hello vm"
            echo "${{ vars.VM_IPV4_ADDRESS }}"
            echo "${{ secrets.VM_HOST }}"
            
      - name: set up docker
        uses: docker/setup-docker-action@v4

      - run : |
            docker pull ${{ secrets.DOCKER_USERNAME }}/todo-application:${{ github.sha }}
            if [ "$(docker ps -a -q -f name=user_todo_app)" ]; then
              docker stop user_todo_app
              docker rm user_todo_app
            fi
            docker run -d --name user_todo_app -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/todo-application:${{ github.sha }}
